# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078902421e26f29188fa7616b293d7646b0a64bfddfc49a1c0d3b90f591aeda017afcf9fb50d0e7036058446bcd2caf1a8904750a720fd5e9a78e3dc54280557

test:
  secret_key_base: dca5e5e73d3568f4213562dd65b843b9965a1eb0231df2f683aa04dd5126b1719b68bf163492c104125e96e76354b76ce3110059b968c00155e9ab977b3748fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
